# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: converter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onverter.proto\x12\tconverter\"#\n\x0cVideoRequest\x12\x13\n\x0byoutube_url\x18\x01 \x01(\t\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32Y\n\x0eVideoConverter\x12G\n\x13\x43onvertVideoToAudio\x12\x17.converter.VideoRequest\x1a\x15.converter.AudioChunk0\x01\x42\x15Z\x13server-go/converterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023server-go/converter'
  _globals['_VIDEOREQUEST']._serialized_start=30
  _globals['_VIDEOREQUEST']._serialized_end=65
  _globals['_AUDIOCHUNK']._serialized_start=67
  _globals['_AUDIOCHUNK']._serialized_end=93
  _globals['_VIDEOCONVERTER']._serialized_start=95
  _globals['_VIDEOCONVERTER']._serialized_end=184
# @@protoc_insertion_point(module_scope)
