# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import converter_pb2 as converter__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in converter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoConverterStub(object):
    """Serviço responsável pela conversão de vídeo para áudio
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertVideoToAudio = channel.unary_stream(
                '/converter.VideoConverter/ConvertVideoToAudio',
                request_serializer=converter__pb2.VideoRequest.SerializeToString,
                response_deserializer=converter__pb2.AudioChunk.FromString,
                _registered_method=True)


class VideoConverterServicer(object):
    """Serviço responsável pela conversão de vídeo para áudio
    """

    def ConvertVideoToAudio(self, request, context):
        """Recebe uma URL do YouTube e retorna o áudio em streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertVideoToAudio': grpc.unary_stream_rpc_method_handler(
                    servicer.ConvertVideoToAudio,
                    request_deserializer=converter__pb2.VideoRequest.FromString,
                    response_serializer=converter__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'converter.VideoConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('converter.VideoConverter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoConverter(object):
    """Serviço responsável pela conversão de vídeo para áudio
    """

    @staticmethod
    def ConvertVideoToAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/converter.VideoConverter/ConvertVideoToAudio',
            converter__pb2.VideoRequest.SerializeToString,
            converter__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
