// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: converter.proto

package converter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoConverterClient is the client API for VideoConverter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoConverterClient interface {
	// Recebe uma URL do YouTube e retorna o áudio em streaming
	ConvertVideoToAudio(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (VideoConverter_ConvertVideoToAudioClient, error)
}

type videoConverterClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoConverterClient(cc grpc.ClientConnInterface) VideoConverterClient {
	return &videoConverterClient{cc}
}

func (c *videoConverterClient) ConvertVideoToAudio(ctx context.Context, in *VideoRequest, opts ...grpc.CallOption) (VideoConverter_ConvertVideoToAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &VideoConverter_ServiceDesc.Streams[0], "/converter.VideoConverter/ConvertVideoToAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoConverterConvertVideoToAudioClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VideoConverter_ConvertVideoToAudioClient interface {
	Recv() (*AudioChunk, error)
	grpc.ClientStream
}

type videoConverterConvertVideoToAudioClient struct {
	grpc.ClientStream
}

func (x *videoConverterConvertVideoToAudioClient) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VideoConverterServer is the server API for VideoConverter service.
// All implementations must embed UnimplementedVideoConverterServer
// for forward compatibility
type VideoConverterServer interface {
	// Recebe uma URL do YouTube e retorna o áudio em streaming
	ConvertVideoToAudio(*VideoRequest, VideoConverter_ConvertVideoToAudioServer) error
	mustEmbedUnimplementedVideoConverterServer()
}

// UnimplementedVideoConverterServer must be embedded to have forward compatible implementations.
type UnimplementedVideoConverterServer struct {
}

func (UnimplementedVideoConverterServer) ConvertVideoToAudio(*VideoRequest, VideoConverter_ConvertVideoToAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method ConvertVideoToAudio not implemented")
}
func (UnimplementedVideoConverterServer) mustEmbedUnimplementedVideoConverterServer() {}

// UnsafeVideoConverterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoConverterServer will
// result in compilation errors.
type UnsafeVideoConverterServer interface {
	mustEmbedUnimplementedVideoConverterServer()
}

func RegisterVideoConverterServer(s grpc.ServiceRegistrar, srv VideoConverterServer) {
	s.RegisterService(&VideoConverter_ServiceDesc, srv)
}

func _VideoConverter_ConvertVideoToAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VideoConverterServer).ConvertVideoToAudio(m, &videoConverterConvertVideoToAudioServer{stream})
}

type VideoConverter_ConvertVideoToAudioServer interface {
	Send(*AudioChunk) error
	grpc.ServerStream
}

type videoConverterConvertVideoToAudioServer struct {
	grpc.ServerStream
}

func (x *videoConverterConvertVideoToAudioServer) Send(m *AudioChunk) error {
	return x.ServerStream.SendMsg(m)
}

// VideoConverter_ServiceDesc is the grpc.ServiceDesc for VideoConverter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoConverter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "converter.VideoConverter",
	HandlerType: (*VideoConverterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConvertVideoToAudio",
			Handler:       _VideoConverter_ConvertVideoToAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "converter.proto",
}
